### ISSUE TITLE
Obtenir les droits d'admins

### ISSUE THREAD

**Issue by Emile76** [Groupe-W/Concerto#1]
-Contacter Cedric
-Lui demander d'installer la liste de logiciels

- OBS WebSockets | https://github.com/Palakis/obs-websocket/releases
- VB audio Software | https://vb-audio.com/Cable/
- OpenStage Control | https://openstagecontrol.ammd.net/
- OBS VirtualCam
- Mettre à jour OBS version > 26

**Comment by gllmAR** [comment]
couper obs ninja, ce n'est pas un logiciel c'est un service web
rajouter obs virtual caméra ou mettre à jour obs à une version supérieur à 26
