### ISSUE TITLE
Trouver un moyen d'intégrer des presets

### ISSUE THREAD

**Issue by Cephalobyte** [Groupe-W/Concerto#10]
Pour éviter une complète cacophonie, trouver un moyen d'appliquer un preset pour
-Une séquence (mélodie)
-Un instrument (ADSR + échantillon)
-Un modulateur (au moins une valeur par défaut)

**Comment by gllmAR** [comment]
pour débutant : 
https://docs.cycling74.com/max8/refpages/preset

pour les intrépides :
https://docs.cycling74.com/max8/refpages/pattrstorage?q=pattr
